/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entidades.Imagem;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.MemoryImageSource;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import rmi.InterfaceRmi;
import static view.Principal.servico;

/**
 *
 * @author edilson
 */
public class ProcessamentoView extends javax.swing.JFrame {

    private Imagem imagem;
    private Image img;
    private int noise;
    private int templateSize;
    private String noiseType;
    private boolean lowpass;
    private int ratio;
    private int modeType;
    private int sigma;
    private int threshold;
    private int threshold2;
    private Principal p;
    private ArrayList<Integer> sizes;
    private int mode;

    /**
     * Creates new form ProcessamentoView
     */
    public ProcessamentoView(Principal p) {
        noise = 0;
        templateSize = 1;
        noiseType = "Gaussian";
        lowpass = false;
        ratio = 5;
        sigma = 1;
        modeType = 1;
        threshold = 5;
        threshold2 = 5;
        sizes = new ArrayList();
        this.p = p;
        mode = 1;

        initComponents();
    }

    private ProcessamentoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTPProcessamento = new javax.swing.JTabbedPane();
        jLPAveraging2 = new javax.swing.JLayeredPane();
        jLTamModelo2 = new javax.swing.JLabel();
        jSTamModelo = new javax.swing.JSlider();
        jLTipoRuido2 = new javax.swing.JLabel();
        jRBGaussian = new javax.swing.JRadioButton();
        jRBCondiment = new javax.swing.JRadioButton();
        jSNoise = new javax.swing.JSlider();
        jLTaxaRuido2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLPFourier = new javax.swing.JLayeredPane();
        jLFiltroF = new javax.swing.JLabel();
        jRBHighPass = new javax.swing.JRadioButton();
        jRBLowPass = new javax.swing.JRadioButton();
        jLRaio = new javax.swing.JLabel();
        jSRaio = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jLPGaussian = new javax.swing.JLayeredPane();
        jLTipoRuidoG = new javax.swing.JLabel();
        jRBGaussianG = new javax.swing.JRadioButton();
        jRBCondimentG = new javax.swing.JRadioButton();
        jLTaxaRuidoG = new javax.swing.JLabel();
        jSNoiseG = new javax.swing.JSlider();
        jLSigma = new javax.swing.JLabel();
        jSTSigma = new javax.swing.JSlider();
        jSRaioG = new javax.swing.JSlider();
        jLRaioG = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLPThresholding = new javax.swing.JLayeredPane();
        jLModo = new javax.swing.JLabel();
        jRBStandard = new javax.swing.JRadioButton();
        jRBHysteresis = new javax.swing.JRadioButton();
        jSThUpper = new javax.swing.JSlider();
        jSThLower = new javax.swing.JSlider();
        jLThLower = new javax.swing.JLabel();
        jLThUpper = new javax.swing.JLabel();
        jLPAveraging3 = new javax.swing.JLayeredPane();
        jLTamModelo3 = new javax.swing.JLabel();
        jSTamModeloM = new javax.swing.JSlider();
        jLTipoRuido3 = new javax.swing.JLabel();
        jRBGaussianM = new javax.swing.JRadioButton();
        jRBCondimentM = new javax.swing.JRadioButton();
        jSNoiseM = new javax.swing.JSlider();
        jLTaxaRuido3 = new javax.swing.JLabel();
        jLPNoMax = new javax.swing.JLayeredPane();
        jLModeNoMax = new javax.swing.JLabel();
        jRBOriginal = new javax.swing.JRadioButton();
        jRBEdge = new javax.swing.JRadioButton();
        jRBThreshold = new javax.swing.JRadioButton();
        jBProcessar = new javax.swing.JButton();
        jCBTamSaida = new javax.swing.JComboBox();
        jLTamSaida = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Processamento");

        jLTamModelo2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLTamModelo2.setText("Tamanho do Modelo:");

        jSTamModelo.setMajorTickSpacing(3);
        jSTamModelo.setMaximum(17);
        jSTamModelo.setMinimum(1);
        jSTamModelo.setMinorTickSpacing(1);
        jSTamModelo.setPaintLabels(true);
        jSTamModelo.setPaintTicks(true);
        jSTamModelo.setSnapToTicks(true);
        jSTamModelo.setValue(1);

        jLTipoRuido2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLTipoRuido2.setText("Tipo de Ruído:");

        jRBGaussian.setText("Gaussian");
        jRBGaussian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBGaussianActionPerformed(evt);
            }
        });

        jRBCondiment.setText("Condiment");
        jRBCondiment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCondimentActionPerformed(evt);
            }
        });

        jSNoise.setMajorTickSpacing(10);
        jSNoise.setMaximum(50);
        jSNoise.setMinorTickSpacing(2);
        jSNoise.setPaintLabels(true);
        jSNoise.setPaintTicks(true);
        jSNoise.setToolTipText("");
        jSNoise.setValue(0);

        jLTaxaRuido2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLTaxaRuido2.setText("Taxa de Ruído: ");

        javax.swing.GroupLayout jLPAveraging2Layout = new javax.swing.GroupLayout(jLPAveraging2);
        jLPAveraging2.setLayout(jLPAveraging2Layout);
        jLPAveraging2Layout.setHorizontalGroup(
            jLPAveraging2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPAveraging2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jLPAveraging2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTipoRuido2)
                    .addComponent(jLTamModelo2)
                    .addComponent(jLTaxaRuido2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPAveraging2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSNoise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLPAveraging2Layout.createSequentialGroup()
                        .addGroup(jLPAveraging2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLPAveraging2Layout.createSequentialGroup()
                                .addComponent(jRBGaussian)
                                .addGap(18, 18, 18)
                                .addComponent(jRBCondiment)
                                .addGap(0, 285, Short.MAX_VALUE))
                            .addComponent(jSTamModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jLPAveraging2Layout.setVerticalGroup(
            jLPAveraging2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPAveraging2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLPAveraging2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipoRuido2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBGaussian)
                    .addComponent(jRBCondiment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPAveraging2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSTamModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTamModelo2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPAveraging2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSNoise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTaxaRuido2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLPAveraging2.setLayer(jLTamModelo2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging2.setLayer(jSTamModelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging2.setLayer(jLTipoRuido2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging2.setLayer(jRBGaussian, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging2.setLayer(jRBCondiment, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging2.setLayer(jSNoise, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging2.setLayer(jLTaxaRuido2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTPProcessamento.addTab("Averaging", jLPAveraging2);

        jLFiltroF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLFiltroF.setText("Filtro: ");

        jRBHighPass.setText("High Pass");
        jRBHighPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBHighPassActionPerformed(evt);
            }
        });

        jRBLowPass.setText("Low Pass");
        jRBLowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBLowPassActionPerformed(evt);
            }
        });

        jLRaio.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLRaio.setText("Raio:");

        jSRaio.setMajorTickSpacing(10);
        jSRaio.setMinimum(5);
        jSRaio.setMinorTickSpacing(5);
        jSRaio.setPaintLabels(true);
        jSRaio.setPaintTicks(true);
        jSRaio.setSnapToTicks(true);
        jSRaio.setToolTipText("");
        jSRaio.setValue(6);

        javax.swing.GroupLayout jLPFourierLayout = new javax.swing.GroupLayout(jLPFourier);
        jLPFourier.setLayout(jLPFourierLayout);
        jLPFourierLayout.setHorizontalGroup(
            jLPFourierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPFourierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLPFourierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLPFourierLayout.createSequentialGroup()
                        .addComponent(jLFiltroF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBHighPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBLowPass))
                    .addGroup(jLPFourierLayout.createSequentialGroup()
                        .addComponent(jLRaio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jLPFourierLayout.setVerticalGroup(
            jLPFourierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPFourierLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jLPFourierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFiltroF)
                    .addComponent(jRBHighPass)
                    .addComponent(jRBLowPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPFourierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRaio)
                    .addComponent(jSRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLPFourier.setLayer(jLFiltroF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFourier.setLayer(jRBHighPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFourier.setLayer(jRBLowPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFourier.setLayer(jLRaio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPFourier.setLayer(jSRaio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLPFourier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLPFourier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTPProcessamento.addTab("Fourier", jPanel2);

        jLTipoRuidoG.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLTipoRuidoG.setText("Tipo de Ruído:");

        jRBGaussianG.setText("Gaussian");
        jRBGaussianG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBGaussianGActionPerformed(evt);
            }
        });

        jRBCondimentG.setText("Condiment");
        jRBCondimentG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCondimentGActionPerformed(evt);
            }
        });

        jLTaxaRuidoG.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLTaxaRuidoG.setText("Taxa de Ruído: ");

        jSNoiseG.setMajorTickSpacing(10);
        jSNoiseG.setMaximum(50);
        jSNoiseG.setMinorTickSpacing(2);
        jSNoiseG.setPaintLabels(true);
        jSNoiseG.setPaintTicks(true);
        jSNoiseG.setToolTipText("");
        jSNoiseG.setValue(0);

        jLSigma.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLSigma.setText("Sigma:");

        jSTSigma.setMajorTickSpacing(3);
        jSTSigma.setMaximum(17);
        jSTSigma.setMinimum(1);
        jSTSigma.setMinorTickSpacing(1);
        jSTSigma.setPaintLabels(true);
        jSTSigma.setPaintTicks(true);
        jSTSigma.setSnapToTicks(true);
        jSTSigma.setValue(1);

        jSRaioG.setMajorTickSpacing(10);
        jSRaioG.setMinimum(5);
        jSRaioG.setMinorTickSpacing(5);
        jSRaioG.setPaintLabels(true);
        jSRaioG.setPaintTicks(true);
        jSRaioG.setSnapToTicks(true);
        jSRaioG.setToolTipText("");
        jSRaioG.setValue(6);

        jLRaioG.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLRaioG.setText("Raio:");

        javax.swing.GroupLayout jLPGaussianLayout = new javax.swing.GroupLayout(jLPGaussian);
        jLPGaussian.setLayout(jLPGaussianLayout);
        jLPGaussianLayout.setHorizontalGroup(
            jLPGaussianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPGaussianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLPGaussianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSigma)
                    .addComponent(jLTaxaRuidoG)
                    .addComponent(jLTipoRuidoG)
                    .addComponent(jLRaioG))
                .addGap(54, 54, 54)
                .addGroup(jLPGaussianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSTSigma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSNoiseG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLPGaussianLayout.createSequentialGroup()
                        .addGroup(jLPGaussianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSRaioG, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLPGaussianLayout.createSequentialGroup()
                                .addComponent(jRBGaussianG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBCondimentG)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLPGaussianLayout.setVerticalGroup(
            jLPGaussianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPGaussianLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jLPGaussianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBGaussianG)
                    .addComponent(jRBCondimentG)
                    .addComponent(jLTipoRuidoG, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPGaussianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSNoiseG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTaxaRuidoG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPGaussianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSTSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSigma, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPGaussianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRaioG)
                    .addComponent(jSRaioG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jLPGaussian.setLayer(jLTipoRuidoG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPGaussian.setLayer(jRBGaussianG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPGaussian.setLayer(jRBCondimentG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPGaussian.setLayer(jLTaxaRuidoG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPGaussian.setLayer(jSNoiseG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPGaussian.setLayer(jLSigma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPGaussian.setLayer(jSTSigma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPGaussian.setLayer(jSRaioG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPGaussian.setLayer(jLRaioG, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLPGaussian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLPGaussian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPProcessamento.addTab("Gaussian", jPanel3);

        jLModo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLModo.setText("Modo: ");

        jRBStandard.setText("Standard");
        jRBStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBStandardActionPerformed(evt);
            }
        });

        jRBHysteresis.setText("Hysteresis");
        jRBHysteresis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBHysteresisActionPerformed(evt);
            }
        });

        jSThUpper.setMajorTickSpacing(25);
        jSThUpper.setMaximum(255);
        jSThUpper.setMinimum(5);
        jSThUpper.setMinorTickSpacing(5);
        jSThUpper.setPaintLabels(true);
        jSThUpper.setPaintTicks(true);
        jSThUpper.setSnapToTicks(true);
        jSThUpper.setValue(5);

        jSThLower.setMajorTickSpacing(25);
        jSThLower.setMaximum(255);
        jSThLower.setMinimum(5);
        jSThLower.setMinorTickSpacing(5);
        jSThLower.setPaintLabels(true);
        jSThLower.setPaintTicks(true);
        jSThLower.setSnapToTicks(true);
        jSThLower.setValue(5);

        jLThLower.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLThLower.setText("TH Lower:");

        jLThUpper.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLThUpper.setText("TH Upper:");

        javax.swing.GroupLayout jLPThresholdingLayout = new javax.swing.GroupLayout(jLPThresholding);
        jLPThresholding.setLayout(jLPThresholdingLayout);
        jLPThresholdingLayout.setHorizontalGroup(
            jLPThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPThresholdingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLPThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLModo)
                    .addComponent(jLThLower)
                    .addComponent(jLThUpper))
                .addGap(107, 107, 107)
                .addGroup(jLPThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLPThresholdingLayout.createSequentialGroup()
                        .addComponent(jRBStandard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBHysteresis)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSThUpper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(jSThLower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLPThresholdingLayout.setVerticalGroup(
            jLPThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPThresholdingLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jLPThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBStandard)
                    .addComponent(jRBHysteresis)
                    .addComponent(jLModo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLPThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSThLower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLThLower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPThresholdingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSThUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLThUpper))
                .addGap(53, 53, 53))
        );
        jLPThresholding.setLayer(jLModo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPThresholding.setLayer(jRBStandard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPThresholding.setLayer(jRBHysteresis, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPThresholding.setLayer(jSThUpper, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPThresholding.setLayer(jSThLower, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPThresholding.setLayer(jLThLower, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPThresholding.setLayer(jLThUpper, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLPThresholding)
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLPThresholding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPProcessamento.addTab("Thresholding", jPanel4);

        jLTamModelo3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLTamModelo3.setText("Tamanho do Modelo:");

        jSTamModeloM.setMajorTickSpacing(3);
        jSTamModeloM.setMaximum(17);
        jSTamModeloM.setMinimum(1);
        jSTamModeloM.setMinorTickSpacing(1);
        jSTamModeloM.setPaintLabels(true);
        jSTamModeloM.setPaintTicks(true);
        jSTamModeloM.setSnapToTicks(true);
        jSTamModeloM.setValue(1);

        jLTipoRuido3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLTipoRuido3.setText("Tipo de Ruído:");

        jRBGaussianM.setText("Gaussian");
        jRBGaussianM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBGaussianMActionPerformed(evt);
            }
        });

        jRBCondimentM.setText("Condiment");
        jRBCondimentM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCondimentMActionPerformed(evt);
            }
        });

        jSNoiseM.setMajorTickSpacing(10);
        jSNoiseM.setMaximum(50);
        jSNoiseM.setMinorTickSpacing(2);
        jSNoiseM.setPaintLabels(true);
        jSNoiseM.setPaintTicks(true);
        jSNoiseM.setToolTipText("");
        jSNoiseM.setValue(0);

        jLTaxaRuido3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLTaxaRuido3.setText("Taxa de Ruído: ");

        javax.swing.GroupLayout jLPAveraging3Layout = new javax.swing.GroupLayout(jLPAveraging3);
        jLPAveraging3.setLayout(jLPAveraging3Layout);
        jLPAveraging3Layout.setHorizontalGroup(
            jLPAveraging3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPAveraging3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jLPAveraging3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTipoRuido3)
                    .addComponent(jLTamModelo3)
                    .addComponent(jLTaxaRuido3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPAveraging3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSNoiseM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLPAveraging3Layout.createSequentialGroup()
                        .addGroup(jLPAveraging3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLPAveraging3Layout.createSequentialGroup()
                                .addComponent(jRBGaussianM)
                                .addGap(18, 18, 18)
                                .addComponent(jRBCondimentM)
                                .addGap(0, 285, Short.MAX_VALUE))
                            .addComponent(jSTamModeloM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jLPAveraging3Layout.setVerticalGroup(
            jLPAveraging3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPAveraging3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLPAveraging3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipoRuido3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBGaussianM)
                    .addComponent(jRBCondimentM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPAveraging3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSTamModeloM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTamModelo3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPAveraging3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSNoiseM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTaxaRuido3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLPAveraging3.setLayer(jLTamModelo3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging3.setLayer(jSTamModeloM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging3.setLayer(jLTipoRuido3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging3.setLayer(jRBGaussianM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging3.setLayer(jRBCondimentM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging3.setLayer(jSNoiseM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPAveraging3.setLayer(jLTaxaRuido3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTPProcessamento.addTab("Median", jLPAveraging3);

        jLModeNoMax.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLModeNoMax.setText("Mode: ");

        jRBOriginal.setText("Original");
        jRBOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBOriginalActionPerformed(evt);
            }
        });

        jRBEdge.setText("Edge");
        jRBEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEdgeActionPerformed(evt);
            }
        });

        jRBThreshold.setText("Threshold");
        jRBThreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBThresholdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLPNoMaxLayout = new javax.swing.GroupLayout(jLPNoMax);
        jLPNoMax.setLayout(jLPNoMaxLayout);
        jLPNoMaxLayout.setHorizontalGroup(
            jLPNoMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPNoMaxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLModeNoMax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBOriginal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBEdge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBThreshold)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jLPNoMaxLayout.setVerticalGroup(
            jLPNoMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPNoMaxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLPNoMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLModeNoMax)
                    .addComponent(jRBOriginal)
                    .addComponent(jRBEdge)
                    .addComponent(jRBThreshold))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jLPNoMax.setLayer(jLModeNoMax, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPNoMax.setLayer(jRBOriginal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPNoMax.setLayer(jRBEdge, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPNoMax.setLayer(jRBThreshold, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTPProcessamento.addTab("NonMax", jLPNoMax);

        jBProcessar.setText("Processar Imagem");
        jBProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProcessarActionPerformed(evt);
            }
        });

        jCBTamSaida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tam. Original" }));
        jCBTamSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTamSaidaActionPerformed(evt);
            }
        });

        jLTamSaida.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLTamSaida.setText("Tamanho da Saída: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPProcessamento)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLTamSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBTamSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBProcessar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPProcessamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLTamSaida)
                        .addComponent(jCBTamSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBProcessar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jRBHysteresisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBHysteresisActionPerformed
        // TODO add your handling code here:
        modeType = 2;
    }//GEN-LAST:event_jRBHysteresisActionPerformed

    private void jRBStandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBStandardActionPerformed
        // TODO add your handling code here:
        modeType = 1;
    }//GEN-LAST:event_jRBStandardActionPerformed

    private void jRBCondimentGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCondimentGActionPerformed
        // TODO add your handling code here:
        noiseType = "Condiment";
    }//GEN-LAST:event_jRBCondimentGActionPerformed

    private void jRBGaussianGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBGaussianGActionPerformed
        // TODO add your handling code here:
        noiseType = "Gaussian";
    }//GEN-LAST:event_jRBGaussianGActionPerformed

    private void jRBLowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBLowPassActionPerformed
        // TODO add your handling code here:
        lowpass = true;
    }//GEN-LAST:event_jRBLowPassActionPerformed

    private void jRBHighPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBHighPassActionPerformed
        // TODO add your handling code here:
        lowpass = false;
    }//GEN-LAST:event_jRBHighPassActionPerformed

    private void jRBGaussianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBGaussianActionPerformed
        // TODO add your handling code here:
        noiseType = "Gaussian";
    }//GEN-LAST:event_jRBGaussianActionPerformed

    private void jRBCondimentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCondimentActionPerformed
        // TODO add your handling code here:
        noiseType = "Condiment";
    }//GEN-LAST:event_jRBCondimentActionPerformed

    private void jRBGaussianMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBGaussianMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBGaussianMActionPerformed

    private void jRBCondimentMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCondimentMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBCondimentMActionPerformed
                          

    private void calculaTamanhos(int width, int height) {
        // TODO add your handling code here:[

        int menorTam = java.lang.Math.min(width, width);
        sizes.add(width);
        for (int i = 2; i <= menorTam; i++) {
            if ((width % i == 0) && (height % i == 0)) {
                jCBTamSaida.addItem((width / i) + " x " + (height / i));
                sizes.add(width / i);
            }
        }

    }
    private void jBProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProcessarActionPerformed
        try {
            img = ImageIO.read(imagem.getImagem());

            Image output = null;

            int tamOutput = sizes.get(jCBTamSaida.getSelectedIndex());
            if (jTPProcessamento.getSelectedComponent().toString().equals("Averaging")) {
                noise = jSNoise.getValue();
                templateSize = jSTamModelo.getValue();

                output = p.servico.averaging(img, noise, noiseType, templateSize, tamOutput);
            } else if (jTPProcessamento.getSelectedComponent().toString().equals("Fourier")) {
                ratio = jSRaio.getValue();
                output = p.servico.fourier(img, lowpass, ratio, tamOutput);
            } else if (jTPProcessamento.getSelectedComponent().toString().equals("Gaussian")) {
                noise = jSNoiseG.getValue();
                ratio = jSRaioG.getValue();
                sigma = jSTSigma.getValue();

                output = p.servico.gaussian(img, noiseType, noise, ratio, sigma, tamOutput);
            } else if (jTPProcessamento.getSelectedComponent().toString().equals("Median")) {
                noise = jSNoiseM.getValue();
                templateSize = jSTamModeloM.getValue();
                if (templateSize < 3) {
                    templateSize = 3;
                }

                output = p.servico.median(img, noise, noiseType, templateSize, tamOutput);
            } else if (jTPProcessamento.getSelectedComponent().toString().equals("Thresholding")) {
                threshold = jSThLower.getValue();
                threshold2 = jSThUpper.getValue();

                output = p.servico.thresholding(img, modeType, threshold, threshold2, tamOutput);
            }
            else if (jTPProcessamento.getSelectedComponent().toString().equals("NonMax")) {

                output = p.servico.nomax(img, mode, tamOutput);
            }
            if (output == null) {
                JOptionPane.showMessageDialog(null, "Erro! Imagem não Processada. Tente novamente...");

            } 
            
        } catch (IOException ex) {
            Logger.getLogger(ProcessamentoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBProcessarActionPerformed

    private void jCBTamSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTamSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTamSaidaActionPerformed

    private void jRBOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBOriginalActionPerformed
        // TODO add your handling code here:
        mode = 1;
    }//GEN-LAST:event_jRBOriginalActionPerformed

    private void jRBThresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBThresholdActionPerformed
        // TODO add your handling code here:
        mode = 3;
    }//GEN-LAST:event_jRBThresholdActionPerformed

    private void jRBEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEdgeActionPerformed
        // TODO add your handling code here:
        mode = 2;
    }//GEN-LAST:event_jRBEdgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcessamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcessamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcessamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcessamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessamentoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBProcessar;
    private javax.swing.JComboBox jCBTamSaida;
    private javax.swing.JLabel jLFiltroF;
    private javax.swing.JLabel jLModeNoMax;
    private javax.swing.JLabel jLModo;
    private javax.swing.JLayeredPane jLPAveraging2;
    private javax.swing.JLayeredPane jLPAveraging3;
    private javax.swing.JLayeredPane jLPFourier;
    private javax.swing.JLayeredPane jLPGaussian;
    private javax.swing.JLayeredPane jLPNoMax;
    private javax.swing.JLayeredPane jLPThresholding;
    private javax.swing.JLabel jLRaio;
    private javax.swing.JLabel jLRaioG;
    private javax.swing.JLabel jLSigma;
    private javax.swing.JLabel jLTamModelo2;
    private javax.swing.JLabel jLTamModelo3;
    private javax.swing.JLabel jLTamSaida;
    private javax.swing.JLabel jLTaxaRuido2;
    private javax.swing.JLabel jLTaxaRuido3;
    private javax.swing.JLabel jLTaxaRuidoG;
    private javax.swing.JLabel jLThLower;
    private javax.swing.JLabel jLThUpper;
    private javax.swing.JLabel jLTipoRuido2;
    private javax.swing.JLabel jLTipoRuido3;
    private javax.swing.JLabel jLTipoRuidoG;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBCondiment;
    private javax.swing.JRadioButton jRBCondimentG;
    private javax.swing.JRadioButton jRBCondimentM;
    private javax.swing.JRadioButton jRBEdge;
    private javax.swing.JRadioButton jRBGaussian;
    private javax.swing.JRadioButton jRBGaussianG;
    private javax.swing.JRadioButton jRBGaussianM;
    private javax.swing.JRadioButton jRBHighPass;
    private javax.swing.JRadioButton jRBHysteresis;
    private javax.swing.JRadioButton jRBLowPass;
    private javax.swing.JRadioButton jRBOriginal;
    private javax.swing.JRadioButton jRBStandard;
    private javax.swing.JRadioButton jRBThreshold;
    private javax.swing.JSlider jSNoise;
    private javax.swing.JSlider jSNoiseG;
    private javax.swing.JSlider jSNoiseM;
    private javax.swing.JSlider jSRaio;
    private javax.swing.JSlider jSRaioG;
    private javax.swing.JSlider jSTSigma;
    private javax.swing.JSlider jSTamModelo;
    private javax.swing.JSlider jSTamModeloM;
    private javax.swing.JSlider jSThLower;
    private javax.swing.JSlider jSThUpper;
    private javax.swing.JTabbedPane jTPProcessamento;
    // End of variables declaration//GEN-END:variables
}
